"""Add daily_rankings table

Revision ID: ce203b07ec81
Revises: 5407b2450f11
Create Date: 2026-02-07 16:11:33.355966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce203b07ec81'
down_revision: Union[str, None] = '5407b2450f11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_rankings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='거래일'),
    sa.Column('stock_code', sa.String(length=10), nullable=False, comment='종목코드'),
    sa.Column('stock_name', sa.String(length=100), nullable=False, comment='종목명'),
    sa.Column('rank', sa.Integer(), nullable=False, comment='순위'),
    sa.Column('current_price', sa.Integer(), nullable=False, comment='현재가'),
    sa.Column('change_price', sa.Integer(), nullable=False, comment='전일대비'),
    sa.Column('change_rate', sa.Float(), nullable=False, comment='등락률'),
    sa.Column('volume', sa.BigInteger(), nullable=False, comment='거래량'),
    sa.Column('trading_value', sa.BigInteger(), nullable=False, comment='거래대금'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date', 'stock_code', name='uq_daily_ranking_date_code')
    )
    op.create_index('idx_trade_date_rank', 'daily_rankings', ['trade_date', 'rank'], unique=False)
    op.create_index(op.f('ix_daily_rankings_id'), 'daily_rankings', ['id'], unique=False)
    op.create_index(op.f('ix_daily_rankings_trade_date'), 'daily_rankings', ['trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_rankings_trade_date'), table_name='daily_rankings')
    op.drop_index(op.f('ix_daily_rankings_id'), table_name='daily_rankings')
    op.drop_index('idx_trade_date_rank', table_name='daily_rankings')
    op.drop_table('daily_rankings')
    # ### end Alembic commands ###
